version: '3.2'
services:
  postgres:
    build:
      context: ./postgres
    ports:
    - "5432:5432"
    environment: 
    -  "POSTGRES_PASSWORD=password"
  api:
    build:
      context: ./api
    volumes: 
      - './api:/usr/src/app'
    environment: 
      -  "PGUSER=postgres"
      -  "PGHOST=postgres"
      -  "PGPASSWORD=password"
      -  "PGPORT=5432"
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    command: yarn run dev