version: '3.2'
services:
  postgres:
    build:
      context: ./postgres
    ports:
    - "5432:5432"
    environment: 
    -  "POSTGRES_PASSWORD=password"
  redis:
      image: redis
      ports: 
      - "6379:6379"
  api:
    build:
      context: ./api
    volumes: 
      - './api:/usr/src/app'
    environment: 
      -  "PGUSER=postgres"
      -  "PGHOST=postgres"
      -  "PGPASSWORD=password"
      -  "PGPORT=5432"
      -  "REDIS_URL=redis://redis:6379"
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
      - redis 
    command: yarn run dev
  prod:
    build:
      context: ./api
    volumes: 
      - './api:/usr/src/app'
    environment: 
      -  "PGUSER=postgres"
      -  "PGHOST=postgres"
      -  "PGPASSWORD=password"
      -  "PGPORT=5432"
      -  "REDIS_URL=redis://redis:6379"
      -  "PORT=3001"
    ports:
      - "3001:3000"
    depends_on: 
      - postgres
      - redis 
    command: yarn run start